/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  collections: {
    usuarios: Usuario;
    fotosUsuarios: FotosUsuario;
    'captura-de-pagos': CapturaDePago;
    imagenes: Imagene;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    fotosUsuarios: FotosUsuariosSelect<false> | FotosUsuariosSelect<true>;
    'captura-de-pagos': CapturaDePagosSelect<false> | CapturaDePagosSelect<true>;
    imagenes: ImagenesSelect<false> | ImagenesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: Usuario & {
    collection: 'usuarios';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  apellidos?: string | null;
  pais?:
    | (
        | 'andorra'
        | 'argentina'
        | 'australia'
        | 'austria'
        | 'bahamas'
        | 'belgica'
        | 'bolivia'
        | 'brasil'
        | 'canada'
        | 'chile'
        | 'china'
        | 'colombia'
        | 'costa_rica'
        | 'croacia'
        | 'cuba'
        | 'chipre'
        | 'republica_checa'
        | 'dinamarca'
        | 'dominica'
        | 'republica_dominicana'
        | 'ecuador'
        | 'egipto'
        | 'el_salvador'
        | 'espana'
        | 'estados_unidos'
        | 'estonia'
        | 'finlandia'
        | 'francia'
        | 'georgia'
        | 'alemania'
        | 'grecia'
        | 'granada'
        | 'guatemala'
        | 'honduras'
        | 'islandia'
        | 'irlanda'
        | 'italia'
        | 'jamaica'
        | 'japon'
        | 'corea_del_sur'
        | 'mexico'
        | 'monaco'
        | 'paises_bajos'
        | 'nueva_zelanda'
        | 'nicaragua'
        | 'noruega'
        | 'panama'
        | 'paraguay'
        | 'peru'
        | 'polonia'
        | 'portugal'
        | 'rusia'
        | 'san_marino'
        | 'serbia'
        | 'singapur'
        | 'eslovaquia'
        | 'eslovenia'
        | 'suecia'
        | 'suiza'
        | 'trinidad_y_tobago'
        | 'turquia'
        | 'ucrania'
        | 'reino_unido'
        | 'uruguay'
        | 'ciudad_del_vaticano'
        | 'venezuela'
      )
    | null;
  numero?: number | null;
  role: 'Admin' | 'User';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fotosUsuarios".
 */
export interface FotosUsuario {
  id: number;
  SupaURL?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "captura-de-pagos".
 */
export interface CapturaDePago {
  id: number;
  SupaURL?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imagenes".
 */
export interface Imagene {
  id: number;
  /**
   *
   *           Describe la imagen de manera clara y precisa para mejorar el SEO, la accesibilidad y destacar la marca Kathy Monzón Cake Studio.
   *           Por ejemplo, si la imagen es de una torta de chocolate, escribe:
   *           "Curso Virtual "Torta de Chocolate"- Torta de chocolate decorada con fresas - Kathy Monzón Cake Studio".
   *
   */
  Alt?: string | null;
  SupaURL?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'fotosUsuarios';
        value: number | FotosUsuario;
      } | null)
    | ({
        relationTo: 'captura-de-pagos';
        value: number | CapturaDePago;
      } | null)
    | ({
        relationTo: 'imagenes';
        value: number | Imagene;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  apellidos?: T;
  pais?: T;
  numero?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fotosUsuarios_select".
 */
export interface FotosUsuariosSelect<T extends boolean = true> {
  SupaURL?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "captura-de-pagos_select".
 */
export interface CapturaDePagosSelect<T extends boolean = true> {
  SupaURL?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imagenes_select".
 */
export interface ImagenesSelect<T extends boolean = true> {
  Alt?: T;
  SupaURL?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}